services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./build:/site
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./caddy/logs:/logs
