name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deploy on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up pnpm
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7 # Specify the version of pnpm you want to use

      # Step 3: Install dependencies with pnpm
      - name: Install dependencies
        run: pnpm install

      # Step 4: Build the SvelteKit app
      - name: Build SvelteKit app
        run: pnpm run build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
